#adapted for nfs storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-n8n-postgresql
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  volumeName: pv-n8n-postgresql
  storageClassName: ""
